# Generated by Django 5.2.7 on 2025-10-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio objetivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
        ),
    ]
