# Generated by Django 5.2.7 on 2025-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
